baseurl: "/"
languageCode: "zh-cn"
title: "Banner Math Note"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: 主页
      url: ""
      weight: 1
    - name: 关于
      url: "about/"
      weight: 2
    - name: 分类
      url: "categories/"
      weight: 3
    - name: 标签
      url: "tags/"
      weight: 4
    - name: 订阅
      url: "index.xml"

params:
  description: "记录学习物理和数学笔记的网站"
  footer: "[周子豪]"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
